# Generated by Django 5.0.7 on 2024-07-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCliente', models.CharField(max_length=150)),
                ('nomeCarro', models.CharField(max_length=150)),
                ('placa', models.CharField(max_length=150)),
                ('dataEntrada', models.DateTimeField(auto_now_add=True)),
                ('dataSaida', models.DateTimeField(null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
